# Generated by Django 4.1.6 on 2023-02-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='checko',
            field=models.BooleanField(default=False),
        ),
    ]
