# Generated by Django 4.1.6 on 2023-02-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_carrinho_checko'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='checko',
            new_name='checkout',
        ),
    ]
