# Generated by Django 4.1.6 on 2023-02-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('score', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
